image: java:8

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build
        caches:
          - gradle
          - maven
          - sdk
          - gradleversion
        script:
          # Setup
          - ./container-setup
          # Build
          - ./gradlew build
          # Archive
          - curl -F "files=@`find amessage/build/outputs/apk/release -name *.apk`" "https://${APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads"
  tags:
    '*.*.*':
      - step:
          deployment: staging
          caches:
            - gradle
            - maven
            - sdk
            - gradleversion
            - googlecloud
          script:
            # Setup
            - ./container-setup
            # Build
            - ./gradlew build assembleAndroidTest
            # Run Connected Tests in Firebase Test Lab
            - ../google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ./amessage/firebase.keys.json
            - ../google-cloud-sdk/bin/gcloud components update
            - ../google-cloud-sdk/bin/gcloud config set project amessage-a4398
            - ../google-cloud-sdk/bin/gcloud firebase test android run --app ./amessage/build/outputs/apk/debug/amessage*.apk --test ./amessage/build/outputs/apk/androidTest/debug/amessage*.apk --device model=Nexus6P,version=25,locale=en,orientation=portrait
            # Publish to Play Store
            - ./gradlew publishRelease
  branches:
    master:
      - step:
          deployment: test
          caches:
            - gradle
            - maven
            - sdk
          script:
            # Setup
            - ./container-setup
            # Build
            - ./gradlew build assembleAndroidTest
            # Run Connected Tests in Firebase Test Lab
            - ../google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ./amessage/firebase.keys.json
            - ../google-cloud-sdk/bin/gcloud components update
            - ../google-cloud-sdk/bin/gcloud config set project amessage-a4398
            - ../google-cloud-sdk/bin/gcloud firebase test android run --app ./amessage/build/outputs/apk/debug/amessage*.apk --test ./amessage/build/outputs/apk/androidTest/debug/amessage*.apk --device model=Nexus6P,version=25,locale=en,orientation=portrait
            # Publish to Play Store
            - ./gradlew publishRelease

definitions:
  caches:
    sdk: ../sdk-tools-linux
    googlecloud: ../google-cloud-sdk
    gradleversion: ./.gradle