const val COMPILE_SDK_VERSION = 28
const val MIN_SDK_VERSION = 24
const val TARGET_SDK_VERSION = 28
const val TEST_ORCHESTRATOR = "ANDROIDX_TEST_ORCHESTRATOR"
const val TEST_RUNNER = "androidx.test.runner.AndroidJUnitRunner"
val TEST_RUNNER_ARGUMENTS = mapOf("clearPackageData" to "true")
const val RELEASE = "release"
const val BETA = "beta"
const val DEBUG = "debug"
const val SHARED_TEST_DIR = "src/sharedTest/java"
const val SOURCE_SET_TEST = "test"
const val SOURCE_SET_ANDROID_TEST = "androidTest"
const val MINIFY = false
const val SHRINK = false
const val PROGUARD_FILE = "proguard-rules.pro"
const val PROGUARD_ANDROID_FILE = "proguard-android-optimize.txt"
