object M {

  const val ABOUT = ":about"
  const val AMESSAGE = ":amessage"
  const val ANALYTICS = ":analytics"
  const val BINDINGS = ":bindings"
  const val COMPONENTS = ":components"
  const val CONNECT = ":connect"
  const val CONNECTION = ":connection"
  const val CONVERSATION = ":conversation"
  const val CONSTANTS = ":constants"
  const val DATABASE = ":database"
  const val DOMAIN = ":domain"
  const val ENCRYPTION = ":encryption"
  const val EXPERIMENTS = ":experiments"
  const val EXPERIMENTSUI = ":experimentsui"
  const val EXTENSIONS = ":extensions"
  const val FEEDBACK = ":feedback"
  const val HANDLE = ":handle"
  const val HELP = ":help"
  const val IDS = ":ids"
  const val NETWORK = ":network"
  const val RES = ":res"
  const val SETTINGS = ":settings"
  const val WINDOWS = ":windows"

}
