version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "amessage/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "amessage/build.gradle" }}
      - run:
          name: Write Keystore File
          command: echo $com_moonlitdoor_amessage_key_store | base64 -d > amessage/build/amessage.keystore.jks
      - run:
          name: Build Release
          command: ./gradlew assembleRelease -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE=./build/amessage.keystore.jks -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE_STORE_PASSWORD=$com_moonlitdoor_amessage_key_store_store_password -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE_KEY_ALIAS=$com_moonlitdoor_amessage_key_store_key_alias -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE_KEY_PASSWORD=$com_moonlitdoor_amessage_key_store_key_password
      - run:
          name: Run Tests
          command: ./gradlew testDebug
      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: amessage/build/reports/tests
          destination: reports
      - store_artifacts:
          path: amessage/build/reports/lint-results.html
          destination: lint
      - store_artifacts:
          path: domain/build/reports/tests
          destination: reportsDomain
      - store_artifacts:
          path: domain/build/reports/lint-results.html
          destination: lintDomain
      - store_test_results:
          path: amessage/build/test-results
      - store_test_results:
          path: domain/build/test-results
