package com.moonlitdoor.amessage.dependencies

object Modules {
  const val ABOUT = ":about"
  const val AMESSAGE = ":amessage"
  const val ANALYTICS = ":analytics"
  const val BINDINGS = ":bindings"
  const val COMPONENTS = ":components"
  const val CONNECT = ":connect"
  const val CONNECTIONS = ":connections"
  const val CONVERSATIONS = ":conversations"
  const val CONSTANTS = ":constants"
  const val DATABASE = ":database"
  const val DOMAIN = ":domain"
  const val DTO = ":dto"
  const val ENCRYPTION = ":encryption"
  const val EXPERIMENTS = ":experiments"
  const val EXPERIMENTS_UI = ":experiments_ui"
  const val EXTENSIONS = ":extensions"
  const val FEEDBACK = ":feedback"
  const val HANDLE = ":handle"
  const val HELP = ":help"
  const val IDS = ":ids"
  const val INIT = ":init"
  const val NETWORK = ":network"
  const val PUSH = ":push"
  const val RESOURCES = ":resources"
  const val ROOT = ":root"
  const val ROUTES = ":routes"
  const val SETTINGS = ":settings"
  const val THEME = ":theme"
  const val WINDOWS = ":windows"
}