name: Android CI

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug
        env:
          com_moonlitdoor_amessage_firebase_debug_default_web_client_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_default_web_client_id }}
          com_moonlitdoor_amessage_firebase_debug_firebase_database_url: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_firebase_database_url }}
          com_moonlitdoor_amessage_firebase_debug_gcm_default_sender_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_gcm_default_sender_id }}
          com_moonlitdoor_amessage_firebase_debug_google_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_api_key }}
          com_moonlitdoor_amessage_firebase_debug_google_app_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_app_id }}
          com_moonlitdoor_amessage_firebase_debug_google_crash_reporting_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_crash_reporting_api_key }}
          com_moonlitdoor_amessage_firebase_debug_google_storage_bucket: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_storage_bucket }}
          com_moonlitdoor_amessage_firebase_debug_project_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_project_id }}
        run: ./gradlew assembleDebug -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_DEFAULT_WEB_CLIENT_ID=$com_moonlitdoor_amessage_firebase_debug_default_web_client_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_FIREBASE_DATABASE_URL=$com_moonlitdoor_amessage_firebase_debug_firebase_database_url -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GCM_DEFAULT_SENDER_ID=$com_moonlitdoor_amessage_firebase_debug_gcm_default_sender_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_API_KEY=$com_moonlitdoor_amessage_firebase_debug_google_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_APP_ID=$com_moonlitdoor_amessage_firebase_debug_google_app_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_CRASH_REPORTING_API_KEY=$com_moonlitdoor_amessage_firebase_debug_google_crash_reporting_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_STORAGE_BUCKET=$com_moonlitdoor_amessage_firebase_debug_google_storage_bucket -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_PROJECT_ID=$com_moonlitdoor_amessage_firebase_debug_project_id
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: ./gradlew test testReport
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: tests
          path: build/reports/allTests
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: ./gradlew lint
      - name: Collect Reports
        run: |
          mkdir ./build/lint
          mv ./about/build/reports/lint-results.html ./build/lint/about-lint-results.html
          mv ./amessage/build/reports/lint-results.html ./build/lint/amessage-lint-results.html
          mv ./analytics/build/reports/lint-results.html ./build/lint/analytics-lint-results.html
          mv ./bindings/build/reports/lint-results.html ./build/lint/bindings-lint-results.html
          mv ./components/build/reports/lint-results.html ./build/lint/components-lint-results.html
          mv ./connect/build/reports/lint-results.html ./build/lint/connect-lint-results.html
          mv ./connections/build/reports/lint-results.html ./build/lint/connections-lint-results.html
          mv ./constants/build/reports/lint-results.html ./build/lint/constants-lint-results.html
          mv ./conversations/build/reports/lint-results.html ./build/lint/conversations-lint-results.html
          mv ./database/build/reports/lint-results.html ./build/lint/database-lint-results.html
          mv ./domain/build/reports/lint-results.html ./build/lint/domain-lint-results.html
          mv ./encryption/build/reports/lint-results.html ./build/lint/encryption-lint-results.html
          mv ./experiments/build/reports/lint-results.html ./build/lint/experiments-lint-results.html
          mv ./experiments_ui/build/reports/lint-results.html ./build/lint/experiments-ui-lint-results.html
          mv ./extensions/build/reports/lint-results.html ./build/lint/extensions-lint-results.html
          mv ./feedback/build/reports/lint-results.html ./build/lint/feedback-lint-results.html
          mv ./handle/build/reports/lint-results.html ./build/lint/handle-lint-results.html
          mv ./help/build/reports/lint-results.html ./build/lint/help-lint-results.html
          mv ./ids/build/reports/lint-results.html ./build/lint/ids-lint-results.html
          mv ./network/build/reports/lint-results.html ./build/lint/network-lint-results.html
          mv ./resources/build/reports/lint-results.html ./build/lint/resources-lint-results.html
          mv ./settings/build/reports/lint-results.html ./build/lint/settings-lint-results.html
          mv ./windows/build/reports/lint-results.html ./build/lint/windows-lint-results.html
      - name: Upload Lint
        uses: actions/upload-artifact@master
        with:
          name: lint
          path: build/lint
