name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      #      - name: Set Up JDK 1.8
      #        uses: actions/setup-java@v1
      #        with:
      #          java-version: 1.8
      - name: List Tags
        run: |
          git fetch --tags --verbose
          git tag
#      - name: AssembleDebug
#        env:
#          com_moonlitdoor_amessage_firebase_beta_default_web_client_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_default_web_client_id }}
#          com_moonlitdoor_amessage_firebase_beta_firebase_database_url: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_firebase_database_url }}
#          com_moonlitdoor_amessage_firebase_beta_gcm_default_sender_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_gcm_default_sender_id }}
#          com_moonlitdoor_amessage_firebase_beta_google_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_api_key }}
#          com_moonlitdoor_amessage_firebase_beta_google_app_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_app_id }}
#          com_moonlitdoor_amessage_firebase_beta_google_crash_reporting_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_crash_reporting_api_key }}
#          com_moonlitdoor_amessage_firebase_beta_google_storage_bucket: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_storage_bucket }}
#          com_moonlitdoor_amessage_firebase_beta_project_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_project_id }}
#        run: ./gradlew assembleDebug -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_DEFAULT_WEB_CLIENT_ID=$com_moonlitdoor_amessage_firebase_beta_default_web_client_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_FIREBASE_DATABASE_URL=$com_moonlitdoor_amessage_firebase_beta_firebase_database_url -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GCM_DEFAULT_SENDER_ID=$com_moonlitdoor_amessage_firebase_beta_gcm_default_sender_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_API_KEY=$com_moonlitdoor_amessage_firebase_beta_google_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_APP_ID=$com_moonlitdoor_amessage_firebase_beta_google_app_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_CRASH_REPORTING_API_KEY=$com_moonlitdoor_amessage_firebase_beta_google_crash_reporting_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_STORAGE_BUCKET=$com_moonlitdoor_amessage_firebase_beta_google_storage_bucket -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_PROJECT_ID=$com_moonlitdoor_amessage_firebase_beta_project_id
