name: Android Beta CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug
        env:
          com_moonlitdoor_amessage_firebase_debug_default_web_client_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_default_web_client_id }}
          com_moonlitdoor_amessage_firebase_debug_firebase_database_url: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_firebase_database_url }}
          com_moonlitdoor_amessage_firebase_debug_gcm_default_sender_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_gcm_default_sender_id }}
          com_moonlitdoor_amessage_firebase_debug_google_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_api_key }}
          com_moonlitdoor_amessage_firebase_debug_google_app_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_app_id }}
          com_moonlitdoor_amessage_firebase_debug_google_crash_reporting_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_crash_reporting_api_key }}
          com_moonlitdoor_amessage_firebase_debug_google_storage_bucket: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_google_storage_bucket }}
          com_moonlitdoor_amessage_firebase_debug_project_id: ${{ secrets.com_moonlitdoor_amessage_firebase_debug_project_id }}
        run: ./gradlew assembleDebug --stacktrace -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_DEFAULT_WEB_CLIENT_ID=$com_moonlitdoor_amessage_firebase_debug_default_web_client_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_FIREBASE_DATABASE_URL=$com_moonlitdoor_amessage_firebase_debug_firebase_database_url -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GCM_DEFAULT_SENDER_ID=$com_moonlitdoor_amessage_firebase_debug_gcm_default_sender_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_API_KEY=$com_moonlitdoor_amessage_firebase_debug_google_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_APP_ID=$com_moonlitdoor_amessage_firebase_debug_google_app_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_CRASH_REPORTING_API_KEY=$com_moonlitdoor_amessage_firebase_debug_google_crash_reporting_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_GOOGLE_STORAGE_BUCKET=$com_moonlitdoor_amessage_firebase_debug_google_storage_bucket -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_DEBUG_PROJECT_ID=$com_moonlitdoor_amessage_firebase_debug_project_id
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: ./gradlew test testReport --stacktrace --continue
      - name: Coverage
        run: ./gradlew jacocoTestReport --stacktrace --continue
      - name: Verify Coverage
        run: ./gradlew jacocoTestCoverageVerification --stacktrace --continue
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: tests
          path: build/reports/allTests
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: build/reports/jacoco/jacocoTestReport/html
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: ./gradlew lint --stacktrace --continue
      - name: Upload Lint
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: lint
          path: amessage/build/reports/lint-results.html
  beta:
    name: Beta
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create Key Directory
        run: mkdir -p ./build/keys
      - name: Write Deploy Keys
        env:
          keys_firebase_type: ${{ secrets.keys_firebase_type }}
          keys_firebase_project_id: ${{ secrets.keys_firebase_project_id }}
          keys_firebase_private_key_id: ${{ secrets.keys_firebase_private_key_id }}
          keys_firebase_private_key: ${{ secrets.keys_firebase_private_key }}
          keys_firebase_client_email: ${{ secrets.keys_firebase_client_email }}
          keys_firebase_client_id: ${{ secrets.keys_firebase_client_id }}
          keys_firebase_auth_uri: ${{ secrets.keys_firebase_auth_uri }}
          keys_firebase_token_uri: ${{ secrets.keys_firebase_token_uri }}
          keys_firebase_auth_provider_x509_cert_url: ${{ secrets.keys_firebase_auth_provider_x509_cert_url }}
          keys_firebase_client_x509_cert_url: ${{ secrets.keys_firebase_client_x509_cert_url }}
        run: |
          echo "{
            \"type\": \"$keys_firebase_type\",
            \"project_id\": \"$keys_firebase_project_id\",
            \"private_key_id\": \"$keys_firebase_private_key_id\",
            \"private_key\": \"$keys_firebase_private_key\",
            \"client_email\": \"$keys_firebase_client_email\",
            \"client_id\": \"$keys_firebase_client_id\",
            \"auth_uri\": \"$keys_firebase_auth_uri\",
            \"token_uri\": \"$keys_firebase_token_uri\",
            \"auth_provider_x509_cert_url\": \"$keys_firebase_auth_provider_x509_cert_url\",
            \"client_x509_cert_url\": \"$keys_firebase_client_x509_cert_url\"
          }" > ./build/keys/firebase-api-key.json
      - name: Write Signing Keys
        env:
          com_moonlitdoor_amessage_key_store: ${{ secrets.com_moonlitdoor_amessage_key_store }}
        run: echo $com_moonlitdoor_amessage_key_store | base64 -d > ./build/keys/amessage.keystore.jks
      - name: Assemble & Deploy Beta
        env:
          COM_MOONLITDOOR_AMESSAGE_PERF: true
          com_moonlitdoor_amessage_firebase_beta_default_web_client_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_default_web_client_id }}
          com_moonlitdoor_amessage_firebase_beta_firebase_database_url: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_firebase_database_url }}
          com_moonlitdoor_amessage_firebase_beta_gcm_default_sender_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_gcm_default_sender_id }}
          com_moonlitdoor_amessage_firebase_beta_google_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_api_key }}
          com_moonlitdoor_amessage_firebase_beta_google_app_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_app_id }}
          com_moonlitdoor_amessage_firebase_beta_google_crash_reporting_api_key: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_crash_reporting_api_key }}
          com_moonlitdoor_amessage_firebase_beta_google_storage_bucket: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_google_storage_bucket }}
          com_moonlitdoor_amessage_firebase_beta_project_id: ${{ secrets.com_moonlitdoor_amessage_firebase_beta_project_id }}
          com_moonlitdoor_amessage_key_store_store_password: ${{ secrets.com_moonlitdoor_amessage_key_store_store_password }}
          com_moonlitdoor_amessage_key_store_key_alias: ${{ secrets.com_moonlitdoor_amessage_key_store_key_alias }}
          com_moonlitdoor_amessage_key_store_key_password: ${{ secrets.com_moonlitdoor_amessage_key_store_key_password }}
        run: |
          curl -L --output $(pwd)/build/bundletool.jar https://github.com/google/bundletool/releases/download/0.11.0/bundletool-all-0.11.0.jar
          ./gradlew amessage:packageBeta bundleBeta -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE=../build/keys/amessage.keystore.jks -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE_STORE_PASSWORD=$com_moonlitdoor_amessage_key_store_store_password -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE_KEY_ALIAS=$com_moonlitdoor_amessage_key_store_key_alias -PCOM_MOONLITDOOR_AMESSAGE_KEY_STORE_KEY_PASSWORD=$com_moonlitdoor_amessage_key_store_key_password -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_DEFAULT_WEB_CLIENT_ID=$com_moonlitdoor_amessage_firebase_beta_default_web_client_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_FIREBASE_DATABASE_URL=$com_moonlitdoor_amessage_firebase_beta_firebase_database_url -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GCM_DEFAULT_SENDER_ID=$com_moonlitdoor_amessage_firebase_beta_gcm_default_sender_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_API_KEY=$com_moonlitdoor_amessage_firebase_beta_google_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_APP_ID=$com_moonlitdoor_amessage_firebase_beta_google_app_id -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_CRASH_REPORTING_API_KEY=$com_moonlitdoor_amessage_firebase_beta_google_crash_reporting_api_key -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_STORAGE_BUCKET=$com_moonlitdoor_amessage_firebase_beta_google_storage_bucket -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_PROJECT_ID=$com_moonlitdoor_amessage_firebase_beta_project_id
          java -jar $(pwd)/build/bundletool.jar build-apks --bundle=./amessage/build/outputs/bundle/beta/$(ls ./amessage/build/outputs/bundle/beta/amessage-*-beta.aab | xargs basename) --output=./amessage/build/temp.apks --ks ./build/keys/amessage.keystore.jks --ks-pass=pass:$com_moonlitdoor_amessage_key_store_store_password --ks-key-alias=$com_moonlitdoor_amessage_key_store_key_alias --key-pass=pass:$com_moonlitdoor_amessage_key_store_key_password --mode=universal
          mv ./amessage/build/temp.apks ./amessage/build/temp.zip
          unzip ./amessage/build/temp.zip -d ./amessage/build/outputs/apk/beta/
          mv ./amessage/build/outputs/apk/beta/universal.apk ./amessage/build/outputs/apk/beta/$(ls ./amessage/build/outputs/apk/beta/amessage-*-beta.apk | xargs basename)
          ./gradlew appDistributionUploadBeta -x packageBeta --stacktrace -PCOM_MOONLITDOOR_AMESSAGE_FIREBASE_BETA_GOOGLE_APP_ID=$com_moonlitdoor_amessage_firebase_beta_google_app_id
